#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WORKDIR = `pwd`

CC = gcc
CXX = g++
AR = ar
LD = g++
WINDRES = windres

INC = 
CFLAGS = -Wall
RESINC = 
LIBDIR = 
LIB = -lcurl
LDFLAGS = 

INC_DEBUG = $(INC)
CFLAGS_DEBUG = $(CFLAGS) -g
RESINC_DEBUG = $(RESINC)
RCFLAGS_DEBUG = $(RCFLAGS)
LIBDIR_DEBUG = $(LIBDIR)
LIB_DEBUG = $(LIB)
LDFLAGS_DEBUG = $(LDFLAGS)
OBJDIR_DEBUG = obj/Debug
DEP_DEBUG = 
OUT_DEBUG = bin/Debug/Mensaplan-C

INC_RELEASE = $(INC)
CFLAGS_RELEASE = $(CFLAGS) -O2
RESINC_RELEASE = $(RESINC)
RCFLAGS_RELEASE = $(RCFLAGS)
LIBDIR_RELEASE = $(LIBDIR)
LIB_RELEASE = $(LIB)
LDFLAGS_RELEASE = $(LDFLAGS) -s
OBJDIR_RELEASE = obj/Release
DEP_RELEASE = 
OUT_RELEASE = ./Mensaplan-C

OBJ_DEBUG = $(OBJDIR_DEBUG)/IO.o $(OBJDIR_DEBUG)/initializer.o $(OBJDIR_DEBUG)/loader.o $(OBJDIR_DEBUG)/main.o $(OBJDIR_DEBUG)/parser.o

OBJ_RELEASE = $(OBJDIR_RELEASE)/IO.o $(OBJDIR_RELEASE)/initializer.o $(OBJDIR_RELEASE)/loader.o $(OBJDIR_RELEASE)/main.o $(OBJDIR_RELEASE)/parser.o

all: debug release

clean: clean_debug clean_release

before_debug: 
	test -d bin/Debug || mkdir -p bin/Debug
	test -d $(OBJDIR_DEBUG) || mkdir -p $(OBJDIR_DEBUG)

after_debug: 

debug: before_debug out_debug after_debug

out_debug: before_debug $(OBJ_DEBUG) $(DEP_DEBUG)
	$(LD) $(LIBDIR_DEBUG) -o $(OUT_DEBUG) $(OBJ_DEBUG)  $(LDFLAGS_DEBUG) $(LIB_DEBUG)

$(OBJDIR_DEBUG)/IO.o: IO.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c IO.c -o $(OBJDIR_DEBUG)/IO.o

$(OBJDIR_DEBUG)/initializer.o: initializer.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c initializer.c -o $(OBJDIR_DEBUG)/initializer.o

$(OBJDIR_DEBUG)/loader.o: loader.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c loader.c -o $(OBJDIR_DEBUG)/loader.o

$(OBJDIR_DEBUG)/main.o: main.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c main.c -o $(OBJDIR_DEBUG)/main.o

$(OBJDIR_DEBUG)/parser.o: parser.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c parser.c -o $(OBJDIR_DEBUG)/parser.o

clean_debug: 
	rm -f $(OBJ_DEBUG) $(OUT_DEBUG)
	rm -rf bin/Debug
	rm -rf $(OBJDIR_DEBUG)

before_release: 
	test -d . || mkdir -p .
	test -d $(OBJDIR_RELEASE) || mkdir -p $(OBJDIR_RELEASE)

after_release: 

release: before_release out_release after_release

out_release: before_release $(OBJ_RELEASE) $(DEP_RELEASE)
	$(LD) $(LIBDIR_RELEASE) -o $(OUT_RELEASE) $(OBJ_RELEASE)  $(LDFLAGS_RELEASE) $(LIB_RELEASE)

$(OBJDIR_RELEASE)/IO.o: IO.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c IO.c -o $(OBJDIR_RELEASE)/IO.o

$(OBJDIR_RELEASE)/initializer.o: initializer.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c initializer.c -o $(OBJDIR_RELEASE)/initializer.o

$(OBJDIR_RELEASE)/loader.o: loader.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c loader.c -o $(OBJDIR_RELEASE)/loader.o

$(OBJDIR_RELEASE)/main.o: main.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c main.c -o $(OBJDIR_RELEASE)/main.o

$(OBJDIR_RELEASE)/parser.o: parser.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c parser.c -o $(OBJDIR_RELEASE)/parser.o

clean_release: 
	rm -f $(OBJ_RELEASE) $(OUT_RELEASE)
	rm -rf $(OBJDIR_RELEASE)

.PHONY: before_debug after_debug clean_debug before_release after_release clean_release

